#!/bin/sh

# Pre-commit hook to copy built files into docs for publishing to Github pages.
# Looks like this can be a bit hit and miss in different versions of Git.
# https://stackoverflow.com/questions/3284292/can-a-git-hook-automatically-add-files-to-the-commit

cd $(git rev-parse --show-toplevel)

cp -a build/web/* docs/
git add docs