#!/bin/sh

# Pre-commit hook to copy built files into docs for publishing to Github pages.
# Looks like this can be a bit hit and miss in different versions of Git.
# https://stackoverflow.com/questions/3284292/can-a-git-hook-automatically-add-files-to-the-commit

cd $(git rev-parse --show-toplevel)

if grep -q '<base href="/">' build/web/index.html 
then
    echo "/docs not added to commit, to refresh build with:"
    echo "   flutter build web --release --base-href '/coingecko-scraper/'"
else
    rm -rf docs/*
    cp -a build/web/* docs/
    git add docs
fi
